### ISSUE TITLE
利用 jekyll + lunrjs 实现 github help 站点的文档结构（支持 conrefs 内容复用），操作步骤说明

### ISSUE THREAD

**Issue by pimgeek** [pimgeek/help-doc#3]
jekyll + lunrjs 的调通方法已经在 #2 中描述过，所以这里只讲实现 github help 站点文档结构的步骤。
### jekyll 环境说明
- 若无特别说明，所有形如 `YYYY-MM-DD-article-title.md` 文档的 Front Matter 中均含有 `title: Article Title`，而且 Front Matter 中的 title 与 _.md 文件名中的 title 严格对应（不区分大小写），_.md 中的 `-` 严格替换为 ` `。
- 我使用的 jekyll 文件夹名为 `help-doc`
- 我使用的 jekyll 模板结构大概如下图所示

```
help-doc/
├── _categories
│   ├── bootcamp.md
│   └── setting-up-and-managing-organizations-and-teams.md
├── _creating_a_new_organization_account
│   ├── 2015-02-08-creating-a-new-organization-from-scratch.md
│   └── 2015-02-09-about-organizations.md
├── css
│   └── ...
├── _data
│   └── conrefs.yml
├── fonts
│   └── ...
├── _includes
│   ├── category-articles.html
│   ├── footer.html
│   ├── header.html
│   ├── head.html
│   ├── search.html
│   ├── sidebar.html
│   └── sub-articles.html
├── _layouts
│   ├── category.html
│   ├── default.html
│   ├── page.html
│   └── post.html
├── _posts
│   ├── 2015-02-10-creating-a-new-organization-account.md
│   ├── 2015-01-01-set-up-git.md
│   └── 2015-01-02-create-a-repo.md
├── _sass
│   └── ...
├── search
│   └── index.html
├── about.md
├── _config.yml
├── feed.xml
└── index.html
```
### 利用 jekyll 构建 github help 站点文档结构的步骤描述
- 帮助文档的 markdown 源码要放在哪里，才能通过 Jekyll 输出到前端？
  先编写文档内容，然后按照 YYYY-MM-DD-help-topic.md 的文件格式命名，最后根据实际情况放进以下两个位置：
  - 对于独立的帮助文档，直接放在 `_posts` 目录下
  - 对于“隶属于”某个独立父帮助文档的“子文档”，根据子文档的实际分类，放在形如 `_category_name` 这样的目录下

---
- 如何让 Jekyll 输出类似 https://help.github.com/articles/set-up-git/ 这样的网址？
  编辑 _config.yml 文档，增加/修改这一行：
  `permalink: /articles/:title/`

---
- 如何让 Jekyll 输出类似 https://help.github.com/categories/bootcamp/ 这样的分类索引页？
  分多个步骤实现：
  - 在已有的，属于 bootcamp 这一类的帮助文档的 markdown 源码 Front Matter 中增加这段内容：
    `categories: ['bootcamp']`
    至少要有一篇属于 bootcamp 分类的帮助文档，才能在首页上列出相关的分类。分类名称支持大写字母、小写字母、空格等，但真正存储到 Jekyll 模板系统的内存中时，**貌似**都会变为小写。
  - 编辑 _config.yml 文档，在其中增加这段定义 collection 的内容：
  
  ``` yml
  collections:
    categories:
      output: true
      permalink: /categories/:path/
  ```
  
  如果不定义这个，仅仅能在首页看到分类索引页的链接，但无法打开目标网页。
  - 在 `_categories` 目录下创建一个名为 `bootcamp.md` 的文件（文件名采用大写字母还是小写会造成不同效果，要注意），其内容如下：
  
  ``` markdown
  ---
  layout: category
  ---
  
  {% assign cat-title-array=page.url | split:'/' %}
  {% assign cat-title=cat-title-array[2] | replace:'-',' ' %}
  {% assign cat-obj=site.categories[cat-title] %}
  {% include category-articles.html which-cat=cat-obj %}   
  ```
  
  如果不定义这个，或者文件名与分类名不一致，仍然会出现导航中有分类索引页的链接，但实际点不开的情况。如果想定义别的分类，比如 `manage-organization` 分类，仍然按这个步骤来做，文件内容不变，只有文件名需要改为 `manage-organization.md` 
  - 在 `_layouts` 目录下创建一个名为 `category.html` 的网页布局文件，其内容如下：
  
  ``` html
  ---
  layout: default
  ---
  
  {% assign page-title-array=page.url | split:'/' %}
  {% assign page-title=page-title-array[2] | replace:'-',' ' | capitalize %}
  
  <h1>Category / {{ page-title }}</h1>
  
  {{ content }}
  ```
  
  单个分类索引网页需要引用这个网页布局文件。
  - 在 `_include` 目录下创建一个名为 `category-articles.html` 的包含文件，其内容如下：
  
  ``` html
  <ul>
  {% for post in include.which-cat %}
    <li>
      <a class="post-link" href="{{ post.url | prepend: site.baseurl | prepend: site.url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
  </ul>
  ```
  
  单个分类索引网页需要引用这个网页包含文件。
  关于 `{% include tmpl.html var-name=sth %}` 和 `{{ include.var-name }}` 这种特殊语法的介绍，请参考 http://jekyllrb.com/docs/templates/ 中的 **ProTip：Use variables as file name**

---
- 如何利用 Jekyll 输出类似于 https://help.github.com/articles/creating-a-new-organization-account/ 这样的 “子文档列表”？
  首先要在 `_posts` 目录下创建一个独立的父帮助文档：`2015-02-10-creating-a-new-organization-account.md`，然后进行下列操作步骤：
  - 修改 `_config.yml` 文件内容，增加一个对应的 collection：
  
  `````` yml
  collections:
  categories:
    output: true
    permalink: /categories/:path/
  creating_a_new_organization_account:  # 这里是新增加的 collection，单词之间必须用 ```_``` 分隔
    output: true
    permalink: /articles/:title/  # 子文档的超链接，以 /articles/xxx-xxx-xxx/ 的方式输出
  ``````
  - 在独立帮助文档 `2015-02-10-creating-a-new-organization-account.md` 的 markdown 源码末尾处增加一段获取子文档列表的代码：
  
  ``` markdown
  ---
  layout: post
  categories: ['Setting up and managing organizations and teams']
  ---
  
  You can create a new organization by either setting up a new organization or converting an existing personal account into an organization.
  
  {% assign coll-title-array=page.url | split:'/' %}
  {% assign coll-title=coll-title-array[2] | replace:'-','_' | downcase %}
  {% assign coll-obj = site.collections[coll-title].docs %}
  {% include sub-articles.html which-coll=coll-obj %}
  ```
  - 在 jekyll 的根目录下创建一个新的 collection 目录： `_creating_a_new_organization_account` ，这里单词之间必须用 `_` 分隔。
  - 在新创建的 collection 目录下增加一系列子文档，均以 markdown 文档方式给出。
  
  ```
  help-doc/
  ├── _creating_a_new_organization_account
  │   ├── 2015-02-08-creating-a-new-organization-from-scratch.md
  │   └── 2015-02-09-about-organizations.md
  ```
  - 在分类索引页的包含文件 `_include/category-articles.html` 中增加下列内容
  
  ``` html
  <ul>
  {% for post in include.which-cat %}
    <li>
      <a class="post-link" href="{{ post.url | prepend: site.baseurl | prepend: site.url }}">{{ post.title }}</a>
        <!-- 如果当前文章有下属的子文章，就顺便列出它们 -->
        {% assign post-id = post.title | replace:' ','_' | downcase %}
        {% if site.collections[post-id].label == post-id %}
          {% assign coll-obj = site.collections[post-id].docs %}
          {% include sub-articles.html which-coll=coll-obj %}
        {% endif %}
       <!-- 子文档列表功能 增加的代码部分结束 -->
    </li>
  {% endfor %}
  </ul>
  ```
  - 在 `_include` 目录下增加一个名为 `sub-articles.html` 的包含文件，其内容如下
  
  ``` html
  <ul>
  {% for post in include.which-coll %}
    <li><a class="post-link" href="{{ post.url | prepend: site.baseurl | prepend: site.url }}">{{ post.title }}</a></li>
  {% endfor %}
  </ul>
  ```
  
  分类索引文件和独立的父文档文件都需要引用这个包含文件。

---
- 如何实现 github help 文档中的 `conrefs` 内容复用？
  - 首先在 jekyll 的源码目录下创建一个 `_data` 目录
  - 在 `_data` 目录下创建 `conrefs.yml` 文件，其内容根据实际需要而定
  
  ``` yml
  repositories:
  create-new:
    1. In the upper-right corner of any page, click {{ octicon-plus }}, and then click **New repository**.
      ![New repository menu](https://help.github.com/assets/images/help/repository/repo-create.png)
  
  wiki:
  click-profile:
    1. ![Profile photo](/assets/images/help/profile/top_right_avatar.png)In the top right corner of any page, click your profile photo, then click **Your profile**.           
  ```
  
  这些就是未来将会被复用的内容片段，只要修改 `conrefs.yml` 文件，并且用 jekyll 重新 build 全站文档，就可以做到一处修改多处生效。
  - 在实际的帮助文档的 markdown 源码中引用这些片段：
  
  ``` markdown
  ### Create a new repository on GitHub                                                                 
  
  {{ site.data.conrefs.repositories.create-new }}
  2. 
  ![Repository name field](/assets/images/help/repository/create-repository-name.png)Create a short, memorable name for your repository. For example, "hello-world".                                                     
  ```
  
  将会被替换为下图所示的样子
  ![](http://i.teamkn.com/i/qhSuTgON.png)
